nuls2:
  chain_id: 1
  enabled: True
  packing_node: False
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_address: NULSd6HgUkssMi6oSjwEn3puNSijLKnyiRV7H
  api_url: https://apiserver.nuls.io/
  explorer_url: https://nuls.world/
  token_contract: NULSd6Hh1FjbnAktH1FFvFnTzfgFnZtgAhYut

ethereum:
  enabled: True
  api_url: http://127.0.0.1:8545
  chain_id: 1
  packing_node: False
  private_key: YOUR_PRIVATE_KEY_HERE
  sync_contract: "0x166fd4299364B21c7567e163d85D78d2fb2f8Ad5"
  start_height: 11474360
  token_contract: "0x27702a26126e0B3702af63Ee09aC4d1A084EF628"
  token_start_height: 10939074

mongodb:
  uri: "mongodb://127.0.0.1"
  database: alephtest

storage:
  store_files: true
  engine: mongodb

ipfs:
  host: 127.0.0.1
  port: 5001
  gateway_port: 8080

aleph:
  queue_topic: ALEPH-TEST

p2p:
  host: 0.0.0.0
  control_port: 4020
  listen_port: 4021
  port: 4025
  http_port: 4024
  reconnect_delay: 60
