  on:
    push:
      branches:
        - '*'

  jobs:
    nix-shell:
      strategy:
        matrix:
          os: [ macos-latest, ubuntu-latest ]
          channel: [ nixos-23.11, nixpkgs-23.11-darwin ]
      runs-on: ${{ matrix.os }}

      steps:
          - uses: actions/checkout@v4
            with:
              # Fetch the whole history for all tags and branches (required for aleph.__version__)
              fetch-depth: 0

          - name: Setup empty config file
            run: touch config.yml

          - name: Set up Nix
            uses: cachix/install-nix-action@v25
            with:
              nix_path: nixpkgs=channel:${{ matrix.channel }}

          - name: Run tests
            run: nix-shell --run "pytest"
